Created new react app for admin
flowacademyhu/piac-app pull request #144
Opened 2021-11-04 15:25 UTC by PatocskaiErik

2021-11-04 15:28 UTC, 6uliver commented
Megpróbáljátok összerakni a CI buildet a frontend mintájára? Itt látszik hogyan csináltam: https://github.com/flowacademyhu/piac-app/blob/develop/.github/workflows/main.yml

2021-11-08 10:41 UTC, taritamas89 commented on admin/public/index.html
> +    <title>React App</title>
ez lehetne valami specifikus is

2021-11-08 11:32 UTC, 6uliver requested changes

2021-11-08 11:32 UTC, 6uliver commented on .github/workflows/main.yml
> +    needs: [build-frontend, build-backend, build-admin]
Ugyanezt adjuk hozzá a live deploy-hoz is.

2021-11-08 13:06 UTC, atttoth approved these changes

2021-11-08 13:33 UTC, 6uliver approved these changes

2021-11-08 13:33 UTC, merged