Implement error pages
flowacademyhu/piac-app pull request #174
Opened 2021-11-08 15:26 UTC by dzsak

2021-11-08 15:33 UTC, mbalyi requested changes

2021-11-08 15:33 UTC, mbalyi commented on frontend/src/components/MarketCardList.js
> +      <ErrorBody error={error} />
ErrorBody-t csak akkor jelenitsuk meg ha van error. igy, hogy itt nincs feltetel, minden esetben ki fog ertekelodni a ErrorBody functional component ami teljesen felesleges, valamint egy ures div is bekerul a DOM-ba szinten feleslegesen. `<div className='error-body'>`

2021-11-08 15:33 UTC, mbalyi commented on frontend/src/pages/VendorProfilePage.js
> +      <ErrorBody error={error} />
itt mar jo a mukodes. csak akkor hivodik meg a komponens ha tenyleg hiba lep fel

2021-11-08 15:33 UTC, mbalyi commented on frontend/src/pages/VendorsByMarketPage.js
> +      <ErrorBody error={error} />
itt is jobb lenne feltetelhez kotni

2021-11-08 17:08 UTC, PatocskaiErik approved these changes

2021-11-08 22:04 UTC, PatocskaiErik approved these changes

2021-11-09 07:01 UTC, mbalyi approved these changes
szep!

2021-11-09 10:33 UTC, 6uliver requested changes
Szerintem jó lesz, csak failel a build, Prettiert futtass rá.

2021-11-09 14:05 UTC, dzsak commented
> Szerintem jó lesz, csak failel a build, Prettiert futtass rá.

igen, ez még a Prettier buildes időszak előtt lett pullhozva a developról, most formázom, és tolom majd be

2021-11-10 11:25 UTC, 6uliver approved these changes

2021-11-10 11:54 UTC, merged