Redesign vendor contact
flowacademyhu/piac-app pull request #181
Opened 2021-11-08 20:38 UTC by dzsak

2021-11-08 21:23 UTC, 6uliver approved these changes
LGTM

2021-11-08 22:02 UTC, PatocskaiErik approved these changes

2021-11-09 10:36 UTC, 6uliver requested changes
Jó lesz, viszont most vettem észre, hogy a social ikonok két helyre is be vannak rakva a repoba. Jobb lenne, ha csak egyszer lennének bent és minden komponens onnan húzná be.

2021-11-09 13:52 UTC, dzsak commented
> Jó lesz, viszont most vettem észre, hogy a social ikonok két helyre is be vannak rakva a repoba. Jobb lenne, ha csak egyszer lennének bent és minden komponens onnan húzná be.

Okés

2021-11-09 14:08 UTC, 6uliver approved these changes

2021-11-09 14:08 UTC, merged