VendorProfile - redesigned product section
flowacademyhu/piac-app pull request #182
Opened 2021-11-08 20:43 UTC by atttoth

2021-11-08 21:21 UTC, 6uliver approved these changes
LGTM

2021-11-09 10:37 UTC, 6uliver requested changes
Conflictot old föl kérlek és utána mehet be.

2021-11-09 12:56 UTC, dzsak approved these changes

2021-11-09 13:00 UTC, 6uliver approved these changes
LGTM

2021-11-09 13:00 UTC, merged