Redesigned header
flowacademyhu/piac-app pull request #183
Opened 2021-11-08 22:03 UTC by PatocskaiErik

2021-11-08 22:50 UTC, 6uliver commented on frontend/src/icons/navigation/calendar-dark-gray.svg
> +  <path id="Icon_awesome-calendar-alt" data-name="Icon awesome-calendar-alt" d="M0,22.656A2.344,2.344,0,0,0,2.344,25H19.531a2.344,2.344,0,0,0,2.344-2.344V9.375H0Zm15.625-9.57a.588.588,0,0,1,.586-.586
Na, ezt én szúrtam el, az ikonok rosszul vannak elnevezve. Ez a sima gray ikon, a gray meg a dark gray. De ha megnézed látod is, a gray-nek kellene világosabbnak lennie, a dark graynek sötétebbnek, szóval cseréljük meg a két calendar file-t.

2021-11-08 22:56 UTC, 6uliver requested changes
A színkód éppen maradhat ebben a PR-ben, de a naptár ikont, amit elszúrtam kérlek cseréld meg.

2021-11-08 22:56 UTC, 6uliver commented on frontend/src/components/Header.js
> +      {location.pathname === "/" ? (
Ne már, erre van a Route komponens, itt a Headeren belül is lehet Routes-ot használni. Egyébként attól, hogy nem "/" a path még nem tuti, hogy az árusok oldalon vagyunk.

2021-11-08 22:56 UTC, 6uliver commented on frontend/src/components/Footer.css
> +  color: #53b896;
Ez másik issue szerintem.

2021-11-09 13:05 UTC, dzsak approved these changes

2021-11-09 13:06 UTC, 6uliver requested changes

2021-11-09 13:06 UTC, 6uliver commented on frontend/src/components/Header.js
> +    <Router>
Ide nem kell még egy Router, elég csak a Switch.

2021-11-09 14:40 UTC, 6uliver approved these changes

2021-11-09 14:40 UTC, merged