Redesign fully market card
flowacademyhu/piac-app pull request #195
Opened 2021-11-09 18:19 UTC by atttoth

2021-11-09 18:28 UTC, 6uliver requested changes
Teszteld végig az oldalakat és rájössz, hogy ugyanabba futottál bele, mint ami a gond ennél a PR-nél: https://github.com/flowacademyhu/piac-app/pull/194

2021-11-09 19:24 UTC, atttoth commented
Vegignéztem a css classokat, a marketHeader-ből 2 van, átneveztem, ha erre gondoltál.

2021-11-09 19:49 UTC, 6uliver commented
> Vegignéztem a css classokat, a marketHeader-ből 2 van, átneveztem, ha erre gondoltál.

Mindegy mire gondolok, teszteld le, amit csináltál és látni fogod, ha valami eltört.

2021-11-10 13:39 UTC, dzsak approved these changes

2021-11-10 14:16 UTC, knorbert-flow approved these changes
Rolanddal megnéztük élőben, mehet

2021-11-10 15:08 UTC, 6uliver approved these changes

2021-11-10 15:09 UTC, merged