E-mail sending from frontend and added token checking for admin component
flowacademyhu/piac-app pull request #209
Opened 2021-11-11 10:00 UTC by PatocskaiErik

2021-11-11 10:06 UTC, dzsak approved these changes
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyYXRpbmciOiJJdCdzIHNvIGFtYXppbmchIn0.w19zTsyaTF1Ih8KqgHItdwIu_qbob60Py-CJWT0Xz_c

2021-11-11 12:36 UTC, 6uliver requested changes
Próbálják meg E2E is tesztelni, kipróbálni, mert a jelenlegi implementáció biztos nem működik ilyen formában.

2021-11-11 12:36 UTC, 6uliver commented on admin/src/App.js
> +  return window.localStorage.getItem("token") ? (
A logika jó, de jobb lenne ezt valami AuthService-be elrejteni.

2021-11-11 12:36 UTC, 6uliver commented on admin/src/App.js
> +          <Route exact path="/" element={<LoginPage />} />
Ha be van jelentkezve, akkor nem akar még egyszer bejelentkezni.

2021-11-11 12:36 UTC, 6uliver commented on admin/src/App.js
> +            element={<TokenExchange />}
Ha nincs bejelentkezve, akkor nem tud bejelentkezni.

2021-11-11 12:36 UTC, 6uliver commented on admin/src/components/VendorTable.js
> +        <Link to="/arus/uj">
Ennek mi köze a loginhoz?

2021-11-11 12:36 UTC, 6uliver commented on admin/src/pages/TokenExchange.js
> +        console.error("Hiba történt a kérés során!");
Ezt a felhasználónak írjuk ki, ne a fejlesztőnek.

2021-11-11 12:36 UTC, 6uliver commented on admin/src/pages/TokenExchange.js
> +        console.log(response);
Itt kellene egy redirect a főoldalra szerintem.

2021-11-11 12:36 UTC, 6uliver commented on admin/src/pages/TokenExchange.js
> +        <Button variant="outline-dark">Belépés</Button>
Itt nem kell form meg gomb, csak valami sima divben egy üzenet, hogy Belépés folyamatban, hiba esetén meg a hibaüzenet.

2021-11-11 12:36 UTC, 6uliver commented on admin/src/pages/VendorDetails.js
> +const VendorDetails = () => {
Enneki mi köze a loginhoz?

2021-11-11 12:37 UTC, 6uliver commented
@PatocskaiErik meg rakj rá kérlek egy frontend mentort is.

2021-11-11 20:48 UTC, 6uliver requested changes

2021-11-11 20:48 UTC, 6uliver commented on admin/src/components/Login.js
> +        );
Szebb lenne suttyó böngészős alert helyett a Küldés gomb alatt egy üzenet HTML-ből.

2021-11-11 20:48 UTC, 6uliver commented on admin/src/components/Login.js
> +        );
A másik, hogy ha elhal az API kérés akkor ne mondjuk azt a felhasználónak, hogy kiment a levél.

2021-11-11 20:48 UTC, 6uliver commented on admin/src/components/Login.js
> +        );
A harmadik, hogy a getMail async, tehát még az API kérés sem fejeződött be, mire már azt mondjuk, hogy megtörtént.

2021-11-11 20:48 UTC, 6uliver commented on admin/src/components/Login.js
> +  const axios = require("axios");
Ne a renderen belül require-öljünk már, tegyük fentre importként.

2021-11-11 20:48 UTC, 6uliver commented on admin/src/components/Menu.js
> +            alert("Sikeresen kijelentkeztél!");
Itt nem kell az alert, érezni fogja a login oldalból, hogy most kijelentkezett.

2021-11-11 20:48 UTC, 6uliver commented on admin/src/pages/TokenExchange.js
> +        window.localStorage.setItem("token", response.data);
Ez is menjen az AuthService-be.

2021-11-11 23:26 UTC, 6uliver requested changes

2021-11-11 23:26 UTC, 6uliver commented on admin/src/components/Menu.js
> +import jwtDecode from "jwt-decode";
Failel a build, mert ezt nem raktad be a package.json-be.

2021-11-11 23:26 UTC, 6uliver commented on admin/src/components/Menu.js
> +  var decoded = jwtDecode(token);
Ez is jobb lenne az AuthService-ben, itt meg csak ennyi: getUsername()

2021-11-12 09:13 UTC, mbalyi commented on admin/src/components/VendorTable.js
> +          <Button style={{ marginTop: "20px", marginBottom: "20px" }}>
itt jobb lenne nem inline css-t hasznalni

2021-11-12 09:14 UTC, mbalyi commented on admin/src/pages/TokenExchange.js
> +    const axios = require("axios");
axiosnak behuzasanak nem az effect-en belul kene lenni. ez azt jelenti hogy minden alkalommal behuzzuk a libet, amikor valtozik a token, vagy ujra renderelodik az oldal.

2021-11-12 09:15 UTC, mbalyi commented on admin/src/pages/TokenExchange.js
> +    async function getMail() {
ezt ki kene szervezni az effecten kivulre

2021-11-12 09:44 UTC, mbalyi approved these changes

2021-11-12 10:14 UTC, 6uliver approved these changes

2021-11-12 10:46 UTC, merged