vendorProfile using margin-bottom
flowacademyhu/piac-app pull request #223
Opened 2021-11-11 14:02 UTC by kovarik85

2021-11-11 14:18 UTC, attilacs reviewed
Jobb oldali padding-et nem látok, az is kellene?

2021-11-11 17:19 UTC, taritamas89 commented on frontend/src/styles/VendorCard.css
> +  padding: 0 20px 0 20px;
`padding: 0 20px;`

2021-11-11 18:10 UTC, 6uliver requested changes
Vizuálisan majdnem jó, a bemutatkozás alatt még óriási az eltartás a többi szekció rendben.

2021-11-12 08:00 UTC, attilacs approved these changes

2021-11-12 08:15 UTC, mbalyi approved these changes

2021-11-12 09:39 UTC, taritamas89 approved these changes

2021-11-12 10:18 UTC, 6uliver approved these changes

2021-11-12 10:19 UTC, merged