Optimisations for search engine
flowacademyhu/piac-app pull request #245
Opened 2021-11-22 16:56 UTC by PatocskaiErik

2021-11-22 17:16 UTC, 6uliver requested changes
Jó lesz így technikailag, két tartalmi észrevételem van.

2021-11-22 17:16 UTC, 6uliver commented on frontend/src/market/profile/MarketInfo.js
> +          {formattedOpeningAndClosingHour}
Bocs, itt lehet nem volt egyértelmű az issue.
A title-ben kellene a piac neve a brand név után: Félpénzzel - Böba baba-mama vásár
És a description lenne a többi: 27 árus - Szálka Halászcsárda és Rendezvényház (Szeged, Közép Kikötő sor 9/A.) - november 21. 09:00 - 14:00

2021-11-22 17:16 UTC, 6uliver commented on frontend/src/vendor/profile/VendorProfilePage.js
> +          {vendor.name}, {vendor.intro}
Itt sem voltam egyértelmű ezek szerint, a name legyen a title, az intro meg a description.

2021-11-22 17:18 UTC, 6uliver requested changes

2021-11-22 17:18 UTC, 6uliver commented on frontend/package-lock.json
> +    "react-helmet": {
Package.json-t is rakd be, ne csak a lockot.

2021-11-22 17:18 UTC, 6uliver commented on frontend/package-lock.json
> +    "react-helmet-async": {
Az async variáns meg nem kell, ha a simát használod.

2021-11-23 12:53 UTC, dzsak approved these changes

2021-11-23 15:05 UTC, 6uliver approved these changes
Két apróság volt még, amiket gyorsan javítottam.

2021-11-23 15:22 UTC, merged