site-240 - Check vendor contacts before rendering
flowacademyhu/piac-app pull request #249
Opened 2021-11-23 16:52 UTC by attilacs

2021-11-23 16:58 UTC, 6uliver requested changes
Jó lesz, két apró clean code észrevételem van csak. Ha megfogadod őket köszönöm, ha nem akkor szólj és nyomom az approve-ot.

2021-11-23 16:58 UTC, 6uliver commented on frontend/src/vendor/profile/contacts/VendorContacts.js
> +        {contacts.map((contact, index) => {
Index az unused variable, töröljük kérlek.

2021-11-23 16:58 UTC, 6uliver commented on frontend/src/vendor/profile/contacts/VendorContacts.js
> +  if (contacts.some((contact) => contact.title)) {
If helyett lehetne &&-el csinálni, mivel az else ág úgy is lényegtelen:

```
return contacts.some((contact) => contact.title) && <VendorPadding> ...
```

vagy olvashatóbban egy változóba kiemelni

```
const hasContact = contacts.some((contact) => contact.title)

return hasContact && <VendorPadding> ...
```

2021-11-24 15:34 UTC, PatocskaiErik approved these changes

2021-11-24 15:52 UTC, merged