Aznapi piac jelenjen meg éjfélig
flowacademyhu/piac-app pull request #274
Opened 2021-11-25 13:20 UTC by dzsak

2021-11-25 15:18 UTC, 6uliver requested changes
Pontosítanék picit, mert 24 éjfél van egy napon: az adott nap éjfélig budapesti időzóna szerint. Ez a megoldás szerintem éjfél és 1 között nem működik télen, nyáron pedig éjfél és 2 között nem.

2021-11-29 11:22 UTC, 6uliver requested changes
Ez még mindig nem az igazi, szerintem bele kellene venni a számításba, hogy az adott pillanat a budapesti időzónában melyik nap és az alapján visszaszámolni a UTC szerinti timestampet.

2021-12-02 15:52 UTC, 6uliver requested changes
Írtam rá integrációs tesztet, ami miatt törik a build. Vagy a teszt rossz vagy az implementáció. Ha a teszt rossz, akkor mutass rá, hogy mi vele a hiba és kijavítjuk.
Ha az implementáció rossz, akkor meg az a feladat, hogy addig kalapáljuk a query-t, amíg zöld nem lesz.
Futtatni lokálisan úgy lehet, hogy ha fut a docker compose-zal a DB-d, akkor parancssorban "mvn test"

2021-12-02 19:38 UTC, dzsak commented
> Írtam rá integrációs tesztet, ami miatt törik a build. Vagy a teszt rossz vagy az implementáció. Ha a teszt rossz, akkor mutass rá, hogy mi vele a hiba és kijavítjuk.
> Ha az implementáció rossz, akkor meg az a feladat, hogy addig kalapáljuk a query-t, amíg zöld nem lesz.
> Futtatni lokálisan úgy lehet, hogy ha fut a docker compose-zal a DB-d, akkor parancssorban "mvn test"

Ránézek majd

2021-12-06 11:51 UTC, 6uliver approved these changes

2021-12-06 11:52 UTC, merged