Site 273 contact info
flowacademyhu/piac-app pull request #279
Opened 2021-11-29 20:04 UTC by attilacs

2021-11-29 20:06 UTC, attilacs commented on frontend/src/vendor/profile/VendorProfileMarkets.tsx
> +  const { data: upcomingMarkets, isLoading } = useQuery<any>(
Gondolom az "any" nem a legjobb, de sajnos nem tudom, hogy itt mi lehet a megfelelő típus.

2021-11-29 20:07 UTC, attilacs commented on frontend/src/market/profile/VendorsByMarketPage.tsx
> +  const { data: market, isLoading } = useQuery<any>(["market", marketId], () =>
Szintén "any".

2021-11-29 20:22 UTC, 6uliver commented on frontend/src/vendor/profile/VendorProfileMarkets.tsx
> +  const { data: upcomingMarkets, isLoading } = useQuery<any>(
Igen, valóban nem szerencsés az any. Itt árus tömb a típus, tehát Market[]. A Market meg lehet egy interface valahol definiálva.

2021-11-30 12:57 UTC, szabogabor91 approved these changes
Totally amazed yet again. Is this reality?

2021-11-30 17:07 UTC, 6uliver requested changes
Írtam pár észrevételt, ami inkább TS-es finomítás, de a kód meg a tesztek nagyon rendben vannak ;)

2021-11-30 17:07 UTC, 6uliver commented on frontend/src/market/profile/VendorlistUploadInProgress.tsx
> +interface vendorListProps {
Az interface-ek neveit nagy betűvel szokás kezdeni a TS-ben.

2021-11-30 17:07 UTC, 6uliver commented on frontend/src/market/profile/VendorsByMarketPage.tsx
> +  interface urlParam {
Az interface-t praktikus lenne a komponens elé kiszedni, valamint a nevét írjuk nagybetűvel.

2021-11-30 17:07 UTC, 6uliver commented on frontend/src/vendor/profile/VendorProfileMarkets.tsx
> +  interface urlParam {
Itt ugyanaz az észrevételem, mint fentebb.

2021-11-30 17:07 UTC, 6uliver commented on frontend/src/vendor/profile/VendorProfileMarkets.tsx
> +  interface marketProps {
Ezt szervezzük ki egy Market.ts-be és a neve lehet az interface-nek Market. A fentebb írt upcomingMarkets típusa pedig Market[] lehet, ilyenkor nem is kell már a lenti map-nél annotálni a függvény paramétert, mert ki fogja találni a TS.
A props postfixet egyébként akkor használjuk a típus nevében, ha a komponens props-ának a típusát jelöljük vele, egyébként nem szoktuk props-nak hívni, ha nem props.

2021-12-02 13:01 UTC, 6uliver approved these changes
@attilacs beszálltam egy kicsit kódolni, találtam egy-két régről húzódó problémát, amiket refactoráltam, ha visszanézed a commitjaim, akkor látod mikbe futottam bele.
Ami a mostnai módosításaiddal kapcsolatos dolgok és átalakítottam őket:
- a Market típus inkább a market mappába került, mert oda tartozik
- kapott a vendor is típust, hogy a vendors ne tetszőleges array legyen
- az AxiosResponse-nál egyszerűbb típusannotáció, ha a metódushívásnak adjuk meg a generikus típust, például axios.get<Market[]>(url)
- az axios-os hívásoknál nem kell, hogy az AxiosResponse típusa undefined is lehessen
- a VendorProfileMarkets-ben már nem is kellett így típusannotáció, hogy a Service metódusai szépen típusosan adják vissza a dolgokat

2021-12-02 13:01 UTC, merged