Feature delete bootstrap dependency
flowacademyhu/piac-app pull request #280
Opened 2021-12-02 14:37 UTC by PatocskaiErik

2021-12-02 14:54 UTC, 6uliver requested changes

2021-12-02 14:54 UTC, 6uliver commented on frontend/src/App.tsx
> -        <QueryClientProvider client={queryClient}>
QueryClientProvider maradjon

2021-12-02 14:54 UTC, 6uliver commented on frontend/src/App.tsx
> -        <QueryClientProvider client={queryClient}>
Amúgy ezért törik a teszt is, megfogta a hibát.

2021-12-02 14:54 UTC, 6uliver commented on frontend/src/footer/Footer.js
> +  const FooterContainer = styled.div`
A styled-component-et sosem render függvényen belül hozzuk létre, ahogy más komponenst sem. Ezt mozgassuk ki a render függény elé.

2021-12-02 14:54 UTC, 6uliver commented on frontend/src/footer/FooterButton.js
> +  const FooterLabel = styled.div`
Szintén, ezek legyenek a render függvény előtt.

2021-12-02 14:54 UTC, 6uliver commented on frontend/src/footer/FooterButton.js
> +    color: #53b896;
Erre egy jobb megoldás, ha a styled-component kap egy prop-ot és akkor az isActive boolean prop alapján cserélgeti a színét. Lásd a doksit, hogy hogyan kell: https://styled-components.com/docs/basics#adapting-based-on-props

2021-12-02 14:54 UTC, 6uliver commented on frontend/src/styles/AppStyled.js
> +.h1, .h2, .h3, .h4, .h5, .h6, h1, h2, h3, h4, h5, h6{
A class-ok nem kellenek, csak a tag selectorok.

2021-12-03 06:29 UTC, 6uliver requested changes
Még egy észrevételt írtam, illetve kérlek az érintett JS file-okat alakítsuk TS-re.

2021-12-03 06:29 UTC, 6uliver commented on frontend/src/footer/Footer.js
> +      <FooterButton requestParam="/arusok" appelation="ÁRUSOK" logo="vendor" />
Csak most láttam meg itt az elnevezéseket, kérlek cseréljük, ha már erre járunk, a "requestParam" helyett egyszerűbb és érthetőbb a "link" vagy "path", az "appelation" helyett meg a "title" vagy "label".

2021-12-03 11:44 UTC, dzsak approved these changes

2021-12-05 10:51 UTC, 6uliver commented on frontend/src/footer/Footer.js
> +      <FooterButton requestParam="/arusok" appelation="ÁRUSOK" logo="vendor" />
Ez még nem oldódott meg.

2021-12-05 11:25 UTC, 6uliver approved these changes

2021-12-05 11:26 UTC, merged